apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mywp
  template:
    metadata:
      labels:
        app: mywp
    spec:
      containers:
      - name: container-wp
        image: 211.183.3.10:5000/mywp:11
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: container-db
        image: 211.183.3.10:5000/mydb:1.0
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: NodePort
  selector:
    app: mywp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32222
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
spec:
  type: NodePort
  selector:
    app: mydb
  ports:
  - port: 3306
